# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-floax'

set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

set -g base-index 1
set -g status-position top
set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 100000
set -g renumber-windows on
set -g set-clipboard on 
setw -g mode-keys vi
set -g mouse on
set -g prefix C-a
set -g prefix2 C-Space
unbind C-b
set -g pane-border-lines heavy
set -g status-left ""
set -g status-left-length 0
set -g set-clipboard on
set -g allow-passthrough on
bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session

# New windows and splits open in cwd
bind c new-window -c "#{pane_current_path}"
bind-key '\' split-window -h -c "#{pane_current_path}"
bind-key '-' split-window -v -c "#{pane_current_path}"

# Status bar styles
set -g status-style "bg=#A3BE8C,fg=#2E3440"
setw -g window-status-format "#[bg=#A3BE8C,fg=#4C566A] #I:#W#{window_flags} #[default]"

setw -g window-status-format "#[fg=#4C566A] #I:#W#{window_flags} "
setw -g window-status-current-style "reverse,bold"
setw -g window-status-current-format " #I:#W#{window_flags} "

# ff — fuzzy file finder popup
bind f display-popup -E -d "#{pane_current_path}" -w 80% -h 80% "zsh -i -c ff"

bind-key "s" display-popup -E -w 80% -h 70% -d '#{pane_current_path}' -T 'Sesh' "zsh -lc 'tv sesh'"
bind-key "g" display-popup -E -w 80% -h 80% -d '#{pane_current_path}' -T 'Worktrunk' "zsh -lc 'tv worktrunk'"

set -g @floax-bind 't'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
