# general
background = '#2e3440'
border_fg = '#3b4252'
text_fg = '#cdcecf'
dimmed_text_fg = '#465780'
# input
input_text_fg = '#bf616a'
result_count_fg = '#bf616a'
# results
result_name_fg = '#81a1c1'
result_line_number_fg = '#ebcb8b'
result_value_fg = '#b48ead'
selection_fg = '#cdcecf'
selection_bg = '#3e4a5b'
match_fg = '#bf616a'
# preview
preview_title_fg = '#c9826b'
# modes
channel_mode_fg = '#2e3440'
channel_mode_bg = '#b48ead'
remote_control_mode_fg = '#2e3440'
remote_control_mode_bg = '#a3be8c'
send_to_channel_mode_fg = '#88c0d0'
